// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuitSupply.Order;

namespace SuitSupply.Order.Migrations
{
    [DbContext(typeof(SuitSupplyContext))]
    partial class SuitSupplyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuitSupply.Order.Domain.Alteration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AlterationLength")
                        .HasColumnType("real");

                    b.Property<int>("AlternationPart")
                        .HasColumnType("int");

                    b.Property<int>("AlternationSide")
                        .HasColumnType("int");

                    b.Property<int>("AlternationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Alteration");
                });

            modelBuilder.Entity("SuitSupply.Order.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinisedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SuitSupply.Order.Domain.Alteration", b =>
                {
                    b.HasOne("SuitSupply.Order.Domain.Order", null)
                        .WithMany("Alterations")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
